{{ config(materialized='external', format =  target.schema) }}
SELECT
  AGE,
  AMONTH,
  AYEAR,
  DHOUR,
  DIED,
  DISP_X,
  DISPUB04,
  DMONTH,
  DQTR,
  DRG,
  DSHOSPID,
  FEMALE,
  HCUP_ED,
  HCUP_OS,
  HISPANIC,
  HOSP_NPI,
  HOSPST,
  I10_DX_Admitting,
  I10_DX1,
  I10_DX2,
  LOS,
  PAY1,
  PSTCO,
  PSTCO2,
  RACE,
  VisitLink,
  ZIP,
  ZIP3,
  ZIPINC_QRTL,
  'sid_core' AS db_file,
  CONCAT_WS('', AYEAR, '-', AMONTH, '-01') AS admit_date,
FROM {{ source('SID', 'NY_SID_2018_CORE') }}

{{ limit_data_in_dev() }}
